server:
  port: 9005

spring:
  application:
    name: movie-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: MyMovieMood

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400

